### ISSUE TITLE
好像不能点击切换到各个市

### ISSUE THREAD

**Issue by xiaodin1** [d3cn/2019-nCoV#1]
作者，我这边下载了您的代码，可以本地很好的展现，但是我看没有点击进入对应的市这个功能，这个是否已经完成这个功能了呢？我这边如果要加的话有能否提供一下思路呢？感谢~~

**Comment by hueidou** [comment]
刚看到网易更新了交互，可点击省区域显示省市地图。你可以参考echarts的示例：https://gallery.echartsjs.com/editor.html?c=xByLjqtaLz

省区域点击事件，重新加载省市地图及数据。geojson需要自己找，或者直接扒网易的，echars不再提供[官方下载](https://www.echartsjs.com/zh/download-map.html)。

**Comment by hueidou** [comment]
找到地图数据了，echarts还有备份，包含国家省市：https://github.com/apache/incubator-echarts/tree/master/map/json
